version: '3.8'
services:
  meeting-room-booking-sys-frontend-vue3:
    image: registry.cn-heyuan.aliyuncs.com/williamdl/meeting-room-booking-sys-frontend-vue3:v0.6
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network

  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3004:3004
    networks:
      - common-network
  mysql-container:
    image: mysql:8.0
    volumes:
      - /Users/liuliang/DockerVolumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 964237
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/liuliang/DockerVolumes/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
